(response-content-type "text/html")
;;Not a valid processing-instruction, technically.
;;#<?xml version='1.0'?>
(unescaped-data "<?xml version='1.0'?>\n")
#<!--This is generated by HelloCgiS-->
#<body>
  &(make-element 'p "The request URI was: " (request-uri))
  <p>&(let ((query (request-query-string)))
        (if query
            (values-append "The query string was: "
			   query)
	    "There was no query string."))</p>
</body>

